# Generated by Django 3.2.6 on 2021-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyawan',
            old_name='nik',
            new_name='nip',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
