# Generated by Django 3.2.7 on 2021-09-06 11:52

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_karyawan_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(upload_to=myapp.models.rename),
        ),
    ]
