# Generated by Django 3.2.5 on 2021-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_harilibur_jabatan_presensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='early_out',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='late_in',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
