# Generated by Django 3.2.5 on 2021-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210923_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shift', models.CharField(max_length=2)),
                ('awal_masuk', models.TimeField()),
                ('masuk', models.TimeField()),
                ('akhir_masuk', models.TimeField()),
                ('awal_pulang', models.TimeField()),
                ('pulang', models.TimeField()),
                ('akhir_pulang', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='karyawan',
            name='shift',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
